<?php

if (!function_exists('ploverwp_primary_header_colors_config')) {
  function ploverwp_primary_header_colors_config() {
    return [
      [
        'control' => '3',
        'id' => 'ploverwp-primary-header-colors-divider',
        'label' => 'Primary Header Colors',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '5',
        'id' => 'ploverwp_header_background_color_popover',
        'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum laudantium consequuntur perferendis sed ullam.',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_header_background_color',
        'default' => '#ffffff',
        'transport' => 'postMessage',
        'label' => 'Header Background Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '5',
        'id' => 'ploverwp_header_site_title_color_popover',
        'content' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptatum laudantium consequuntur perferendis sed ullam.',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_header_site_title_color',
        'default' => '#000000',
        'transport' => 'postMessage',
        'label' => 'Site Title Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_header_tagline_color',
        'default' => '#000000',
        'transport' => 'postMessage',
        'label' => 'Tagline Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '3',
        'id' => 'ploverwp-primary-header-divider',
        'label' => 'Menu',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_menu_item_color',
        'default' => '#000000',
        'transport' => 'postMessage',
        'label' => 'Items Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_menu_item_hover_color',
        'default' => '#47b2e4',
        'transport' => 'postMessage',
        'label' => 'Items Hover Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_menu_active_item_color',
        'default' => '#47b2e4',
        'transport' => 'postMessage',
        'label' => 'Active Item Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '3',
        'id' => 'ploverwp-primary-header-sub-menu-divider',
        'label' => 'Sub Menu',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_sub_menu_background_color',
        'default' => '#ffffff',
        'transport' => 'postMessage',
        'label' => 'Background Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '3',
        'id' => 'ploverwp-primary-header-mobile-menu-divider',
        'label' => 'Mobile Menu',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_mobile_menu_toggle_color',
        'default' => '#000000',
        'transport' => 'postMessage',
        'label' => 'Toggle Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_mobile_menu_background_color',
        'default' => '#ffffff',
        'transport' => 'postMessage',
        'label' => 'Background Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_mob_menu_item_color',
        'default' => '#000000',
        'transport' => 'postMessage',
        'label' => 'Items Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_mob_menu_item_hover_color',
        'default' => '#47b2e4',
        'transport' => 'postMessage',
        'label' => 'Items Hover Color',
        'section' => 'section-primary-header',
      ],
      [
        'control' => '2',
        'id' => 'ploverwp_primary_header_mob_menu_active_item_color',
        'default' => '#47b2e4',
        'transport' => 'postMessage',
        'label' => 'Active Item Color',
        'section' => 'section-primary-header',
      ],
    ];
  }
}